name: Update Subscription

on:
  schedule:
    - cron: '*/50 * * * *' # تنظیم شده برای اجرا در فواصل ۵۰ دقیقه‌ای
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and Modify Configs
        run: |
          curl -s "https://raw.githubusercontent.com/masir-sefid/Sub/main/@Masir_Sefid.txt" > temp.txt
          sed -E 's/(#[^[:space:]\\]*)/#ZeroxVPN/g' temp.txt > sub.txt
          rm temp.txt

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sub.txt
          git commit -m "Update configs with ZeroxVPN name" || exit 0
          git push
