name: Update Subscription

on:
  schedule:
    - cron: '0 */6 * * *' # هر ۶ ساعت یک‌بار به صورت خودکار آپدیت می‌شود
  workflow_dispatch: # امکان آپدیت دستی را به شما می‌دهد

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and Modify Configs
        run: |
          # دانلود فایل از لینک مبدا
          curl -s "https://raw.githubusercontent.com/masir-sefid/Sub/main/@Masir_Sefid.txt" > temp.txt
          
          # جایگزینی تمام نام‌های بعد از # با ZeroxVPN
          sed -E 's/(#[^[:space:]\\]*)/#ZeroxVPN/g' temp.txt > sub.txt
          
          # پاک کردن فایل موقت
          rm temp.txt

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sub.txt
          git commit -m "Update configs with ZeroxVPN name" || exit 0
          git push

